# Generated by Django 4.2.2 on 2023-06-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordetails',
            name='website_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
