# Generated by Django 4.2.2 on 2023-07-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creatordetails_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordetails',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creatordetails',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
