# Generated by Django 4.2.2 on 2023-06-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authordetails_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreaterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('website_link', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AuthorDetails',
        ),
    ]
