# Generated by Django 4.2.9 on 2024-01-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creatordetails_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatordetails',
            name='is_staff',
        ),
    ]
