# Generated by Django 4.2.2 on 2023-07-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_creatordetails_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatordetails',
            name='website_link',
        ),
    ]
