# Generated by Django 4.2.2 on 2023-06-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_createrdetails_delete_authordetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createrdetails',
            name='password',
        ),
    ]
