# Generated by Django 4.2.2 on 2023-07-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_creatordetails_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatordetails',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
