# Generated by Django 4.2.2 on 2023-06-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_description_createrdetails_tech_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createrdetails',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='createrdetails',
            name='lastname',
        ),
        migrations.AddField(
            model_name='createrdetails',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='createrdetails',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
